name = "Rinixized"
author = "Rinix"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98690a1ff458b214e7f2121dc24a090e8e1b6f23f3903af4e71810d2deb11a99"

[versions]
minecraft = "1.19.2"
quilt = "0.17.11"

[options]
acceptable-game-versions = ["1.19.1", "1.19.2"]
