name = "Rinixized"
author = "Rinix"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "155ee0daaa979e874a3893775dd1ec9a0656be9af1008fc7eda1cc4b85c598f3"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1"

[options]
acceptable-game-versions = ["1.19.1", "1.19.2"]
