name = "Rinixized"
author = "Rinix"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39ae5227f7588052f81e54859e96ec41a935c10f395398dfbed3fc2e134157d9"

[versions]
minecraft = "1.19.2"
quilt = "0.18.1"

[options]
acceptable-game-versions = ["1.19.1", "1.19.2"]
