name = "Rinixized"
author = "Rinix"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "becc8358d43aca18c7210d3dfb3b71fb4cc1ddafa5537d2cdba2bb786a0114ca"

[versions]
minecraft = "1.19.3"
quilt = "0.18.3"
