name = "Rinixized"
author = "Rinix"
version = "1.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64e61248e7d8190ba3f3669708db410f477c52a6501d65f3eb4f90a986b04a5a"

[versions]
minecraft = "1.19.3"
quilt = "0.17.11"
