name = "Rinixized"
author = "Rinix"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "562b29d92d1ac16f5bf533a1ecff586b9a0e9a127d80aab28540780701ec288f"

[versions]
minecraft = "1.19.3"
quilt = "0.17.11"
