name = "Rinixized"
author = "Rinix"
version = "1.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c370eb7a75d0a334bdbfba7b63e9855d9cdf462c8d198bc1c44357fc80ef33d7"

[versions]
minecraft = "1.19.3"
quilt = "0.18.3"
