name = "Rinixized"
author = "Rinix"
version = "1.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f10d0530b9506c804509947c51483e1861803bcdd8a19542ad0b3adbea4c261"

[versions]
minecraft = "1.19.3"
quilt = "0.18.5"
