name = "Rinixized"
author = "Rinix"
version = "1.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ad7d324f9857c16088990049c9a4d2bd25538319c8d80759d4cc5c3cc04edbc"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
