name = "Rinixized"
author = "Rinix"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c07d9ce21ab863b84ea60d8227104200ae6bea9a597403fcea29e3c012b4b8dd"

[versions]
minecraft = "1.19.3"
quilt = "0.18.10"
