name = "Rinixized"
author = "Rinix"
version = "1.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bff3972693616bf385380015168ae442ba25df3d5ed398df57d00f9c5e93c42"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
