name = "Rinixized"
author = "Rinix"
version = "1.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddc8cfaca82086dc73ca270662c197d40497f1e945795634a863032a3cd6445e"

[versions]
minecraft = "1.19.3"
quilt = "0.18.3"
