name = "Rinixized"
author = "Rinix"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6dc25632bdc28bbcc7b278f9074b38c655f3860484e4cef58fbaeac2f9f60cb"

[versions]
minecraft = "1.19.3"
quilt = "0.17.11"
