name = "Rinixized"
author = "Rinix"
version = "1.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fad4487a53668d21bcf4efbf9c35d926dbb44aff21d06898bce1c2be71dc186d"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1"
