name = "Rinixized"
author = "Rinix"
version = "1.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc311548e8211b22ffb6384e630cda206b6d18c37bc77b8b58c3d810e3498257"

[versions]
minecraft = "1.19.3"
quilt = "0.18.6"
