name = "Rinixized"
author = "Rinix"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddbbc4b312d2467ba1f4882d7037454778081f50716c24f666ea704dccb8f54f"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
