name = "Rinixized"
author = "Rinix"
version = "4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b55220cf0400111a11bf7e8635572dab5a9514ee73f2ee71945cf5636314d2e"

[versions]
minecraft = "1.20.1"
quilt = "0.19.2"
