name = "Rinixized"
author = "Rinix"
version = "3.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0490851e5ce57c0eb094be2c44650809b2ecb8c504ee6d04545c1d3b558e0139"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
