name = "Rinixized"
author = "Rinix"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "398950d5de9381936f8e2c7133ee5af7963b8dd84671706d20e9e49b2a755af6"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
