name = "Rinixized"
author = "Rinix"
version = "3.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa59f01680a62f21dec01794d5b4ea6c2d16ccabe045380dc775ecaf258d1dd0"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
