name = "Rinixized"
author = "Rinix"
version = "3.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "344f0e9c57fca685c1cb7155288838c74070fe22b51a865b803f87379fcbb12c"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
