name = "Rinixized"
author = "Rinix"
version = "3.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aac2bca546fb9f00306129cf300c41317031ad61191f6e15f094f733e58a5cd4"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
