name = "Rinixized"
author = "Rinix"
version = "3.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85287e048b48b277c70e95ace5c05d864a42cf3aabf429fa5aa98e33b0175887"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
