name = "Rinixized"
author = "Rinix"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "874d4556be214cd86c37bae6e675555a9b361b5c2997cfa5aab9104389c0569d"

[versions]
minecraft = "1.19.4"
quilt = "0.18.10"
